In [105]:
# Tensorflow 환경 확인
import tensorflow as tf

# 사용 가능 메소드 목록 출력
dir(tf)

['AUTO_REUSE',
 'AggregationMethod',
 'Assert',
 'AttrValue',
 'COMPILER_VERSION',
 'ConditionalAccumulator',
 'ConditionalAccumulatorBase',
 'ConfigProto',
 'DType',
 'DeviceSpec',
 'Dimension',
 'Event',
 'FIFOQueue',
 'FixedLenFeature',
 'FixedLenSequenceFeature',
 'FixedLengthRecordReader',
 'GIT_VERSION',
 'GPUOptions',
 'GRAPH_DEF_VERSION',
 'GRAPH_DEF_VERSION_MIN_CONSUMER',
 'GRAPH_DEF_VERSION_MIN_PRODUCER',
 'Graph',
 'GraphDef',
 'GraphKeys',
 'GraphOptions',
 'HistogramProto',
 'IdentityReader',
 'IndexedSlices',
 'InteractiveSession',
 'LMDBReader',
 'LogMessage',
 'MetaGraphDef',
 'NameAttrList',
 'NoGradient',
 'NodeDef',
 'NotDifferentiable',
 'OpError',
 'Operation',
 'OptimizerOptions',
 'PaddingFIFOQueue',
 'Print',
 'PriorityQueue',
 'QUANTIZED_DTYPES',
 'QueueBase',
 'RandomShuffleQueue',
 'ReaderBase',
 'RegisterGradient',
 'RunMetadata',
 'RunOptions',
 'Session',
 'SessionLog',
 'SparseConditionalAccumulator',
 'SparseFeature',
 'SparseTensor',
 'SparseTensorValue

In [21]:
# 텐서플로 버전 확인: Version 확인을 통해 하위호환성 지원이 되지 않는 tensorflow의 api 확인
tf.__version__

'1.4.1'

### Tensorflow 요소 ([참조](https://gist.github.com/haje01/202ac276bace4b25dd3f))
- Operation(오퍼레이션, op)
  + 그래프 상의 노드를 op(operation)라 부름
  + op는 하나 이상의 tensor를 받을 수 있다.
  + 오퍼레이션은 계산을 수행하고, 결과를 하나 이상의 텐서로 반환할 수 있음
- Tensor(텐서)
  + Tensor는 학습 데이터가 저장되는 일종의 다차원 배열
  + 내부적으로 모든 데이터는 텐서를 통해 표현됨
  + 그래프 내의 오퍼레이션 간에는 텐서만이 전달된다.
- Session (세션)
  + 그래프를 실행하기 위해서는 세션 객체가 필요
  + session은 op의 실행환경을 캡슐화한 것
- Variable (변수)
  + 변수는 그래프의 실행시 파라미터를 저장하고 갱신되는데 사용됨
  + 메모리 상에서 텐서를 저장하는 버퍼 역할을 함

### Data Flow Graph
TensorFlow는 계산 정의와 실행을 분리한다.
- Phase1: assemble a graph (tensor board 활용)
- Phase2: 세션을 사용하여 그래프에서 작업을 실행

WHY???

### Tensor란 무엇인가?

an N-dimensional matrix
0-d tensor: scalar(number)
1-d tensor: vector
2-3 tensor: matrix

In [53]:
#Gradient Descent로 인자 찾아내기
import tensorflow as tf
import numpy as np

# Numpy random으로 100개의 가짜 데이터 2개 만들기(100개짜리 배열 2개 나옴)
a_data = np.float32(np.random.rand(2,100))

# Learning label은 아래 식으로 산출
# Y = W * x + b (W = [0.1, 0.2], b=0.3, x=a_data, y=b_data)
# y = [0.1,0.2] * a_data + 0.3

b_data = np.dot([0.100,0.200], a_data) + 0.300

# print("mat1")
# print([0.100,0.200])
# print("a_data")
# print(a_data)
# print("b_data")
# print(b_data)

mat1
[0.1, 0.2]
a_data
[[0.9762948  0.37952888 0.452812   0.3732571  0.5724809  0.3926091
  0.37224716 0.12613295 0.5443784  0.51313823 0.89395654 0.08926325
  0.56532985 0.81026584 0.630753   0.5662842  0.0551     0.33473718
  0.35671464 0.23493029 0.11713364 0.9769753  0.2521702  0.44452682
  0.56928754 0.9723843  0.00863212 0.99033237 0.95040536 0.5675956
  0.00454839 0.1375609  0.7843575  0.17149347 0.89348924 0.960908
  0.2320544  0.6473265  0.5644025  0.9853086  0.7602831  0.1435928
  0.03506232 0.49066806 0.61099774 0.81680095 0.87129897 0.412714
  0.42060623 0.35008848 0.41222942 0.48614222 0.11366674 0.96767324
  0.03570095 0.6780595  0.35426927 0.24742052 0.02081764 0.28836098
  0.19573632 0.75208914 0.42270505 0.78598464 0.5872347  0.03399086
  0.02793236 0.2738746  0.04930761 0.56893843 0.4466785  0.05829671
  0.10368086 0.16442713 0.852234   0.18231253 0.87866163 0.82344925
  0.35456577 0.70072615 0.19564019 0.7077101  0.75587976 0.084523
  0.43654284 0.71686244 0.08102257

In [78]:
# python 기초 - 선형대수 다뤄보기

# array 생성
arr = np.array([[1,2],[3,4]])
print('arr\n', arr)

# 전치행렬 구하기
arrT = arr.T
print('arrT\n', arrT)

# 행렬곱 구하기
c = np.dot(arr,arrT)
print('np.dot(arr,arrT)\n', c)


arr
 [[1 2]
 [3 4]]
arrT
 [[1 3]
 [2 4]]
np.dot(arr,arrT)
 [[ 5 11]
 [11 25]]


In [85]:
# 다음의 식을 행렬로 표현하고 변수의 해를 구하라
# 3x1 + 2x2 +  x2 = 7
#  x1 -  x2 + 3x3 = 3
# 5x1 + 4x2 - 2x3 = 1

a = np.array([[3,2,1],[1,-1,3],[5,4,-2]])
b = np.array([7,3,1])
print('a\n',a)
print('b\n',b)

# 행렬의 해를 구하는 방법
x = lin.solve(a,b)
print('lin.solve(a,b)\n',x)

a
 [[ 3  2  1]
 [ 1 -1  3]
 [ 5  4 -2]]
b
 [7 3 1]
lin.solve(a,b)
 [-3.  6.  4.]


In [67]:

import numpy as np
import numpy.linalg as lin

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[0,1,-1],[1,1,0]])
# x
print('x = \n', x)
# y
print('y = \n', y)
# y.T
print('y.T = \n', y.T)

# dot
print('np.dot(x,y.T) = \n', np.dot(x,y.T))

x = 
 [[1 2 3]
 [4 5 6]]
y = 
 [[ 0  1 -1]
 [ 1  1  0]]
y.T = 
 [[ 0  1]
 [ 1  1]
 [-1  0]]
np.dot(x,y.T) = 
 [[-1  3]
 [-1  9]]
sample
 [[1 2]
 [3 4]]
sample.T
 [[1 3]
 [2 4]]


`y = wx + b`
- y: result
- w: weight
- x: input
- b: bias


### Tensorflow Operations
- Basic Operations
- Tensor Types
- Project speed dating
- Placeholders and feeding inputs
- Lazy loading


In [1]:
# Tensorflow basic operation
# https://www.tensorflow.org/api_docs/python/

import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

In [2]:
with tf.Session() as sess:
    sess.run(x)
    writer = tf.summary.FileWriter("/tmp/tb", sess.graph)
writer.close()

TensorBoard를 활용하여 모델을 튜닝할 factor를 찾을 수 있고 이를 통해 bagging과 boosting 여부를 결정할 수 있다.

Bagging(Bootstrap Aggregating)
- bootstrap 샘플링 방법을 이용해서 여러개의 트레이닝 데이터를
생성하는 방법이다. 이렇게 생성된 데이터 셋은 하나의 모델을 생성

Boosting
- 약한 learner들을 합쳐서 강한 learner로 만들어주는 알고리즘을 말한다.